platform :ios, "7.0"

pod 'AFNetworking', "~> 2.0"
pod 'SDWebImage', '~> 3.5'
pod 'DTCoreText', '~> 1.6.8'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MagicalRecord', '~> 2.2'
