platform :ios, "7.0"

pod 'AFNetworking', '~> 2.2.4'
pod 'SDWebImage', '~> 3.6'
pod 'DTCoreText', '~> 1.6.11'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MagicalRecord', '~> 2.2'
pod 'DateTools'
